### ISSUE TITLE
Is it advantageous to have Boost installed?

### ISSUE THREAD

**Issue by danmichaelo** [28msec/zorba#143]
It is not mentioned in the [Prerequisites for Building Zorba](http://www.zorba.io/documentation/latest/zorba/build/build_prerequisites/), but Cmake checks for it, and it's mentioned in the [Install notes for Mac OS X](https://github.com/28msec/zorba/blob/master/doc/zorba/install_osx.dox). I'm putting together [a formula](https://github.com/Homebrew/homebrew/pull/36416) for installing Zorba on Mac OS X through Homebrew, and I'm wondering if there is any reason to recommend having Boost installed or not.

**Comment by fcavalieri** [comment]
Hello @danmichaelo , 
the boost libraries are not required for building or running zorba. The only part of zorba that uses boost  is the multithreaded testdriver. If boost is not found the testdriver will be single thread. Having boost installed thus only helps people who develop a lot and would be happy of saving a few seconds when  running the ctest after having done some changes.

HTH,
Federico

**Comment by danmichaelo** [comment]
Great, thanks for clarifying!
