### ISSUE TITLE
php 5.5 segfault

### ISSUE THREAD

**Issue by fcavalieri** [28msec/zorba#157]
PHP 5.5 test10

**Comment by wcandillon** [comment]
Nop. I will remove disable the SWIG tests. From the zorba mailing-list it looks like no one is able to use it anyways. And we want to provide Zorba as a docker microservice. This is how people will use it from PHP in the futur.

**Comment by fcavalieri** [comment]
@wcandillon Do you also want not track the existence of this bug? The underlying issue might be unrelated

**Comment by wcandillon** [comment]
I don't see why we would look into it but maybe I'm missing something.

On Wed, Apr 8, 2015 at 7:27 AM, Federico Cavalieri <notifications@github.com

**Comment by fcavalieri** [comment]
The bug which causes this exists regardless of whether php 5.5 is used.
With php 5.5 it is apparent in test 10, but in other versions it might
appear in different situations.

**Comment by fcavalieri** [comment]
Unless we drop 100% of swig integration of course

**Comment by wcandillon** [comment]
We drop it 100%.

On Wed, Apr 8, 2015 at 7:39 AM, Federico Cavalieri <notifications@github.com
> wrote:

> Unless we drop 100% of swig integration of course
>
> On Wed, Apr 8, 2015 at 4:34 PM, Federico Cavalieri <

**Comment by wcandillon** [comment]
Dropping is a strong word, we never really supported it.

**Comment by fcavalieri** [comment]
It is a good news, supporting it would consume a lot of energy for what it
is worth.
